ok-->ALTER TABLE SPILLER DROP COLUMN "BILDE" ;

ok-->ALTER TABLE "ROSENHOFF"."PUBLIC"."SPILLER" ADD "IMAGE_EXTENSION" varchar(6) NULL ;


--CREATE TABLE "PUBLIC"."POLL"
--(
--   ID integer PRIMARY KEY NOT NULL,
--   AKTIVITET_ID integer NOT NULL,
--   LABEL varchar(10) DEFAULT 'TEST',
--   SPILLER_ID integer NOT NULL,
--   KOMMER boolean NOT NULL
--)
--;
--ALTER TABLE "PUBLIC"."POLL"
--ADD CONSTRAINT FK_POLL_AKTIVITET
--FOREIGN KEY (AKTIVITET_ID)
--REFERENCES "PUBLIC"."AKTIVITET"(AKTIVITET_ID)
;
--CREATE INDEX FK_POLL_AKTIVITET_INDEX_2 ON "PUBLIC"."POLL"(AKTIVITET_ID)
;
--CREATE UNIQUE INDEX PRIMARY_KEY_B8 ON "PUBLIC"."POLL"(ID)
;



--ALTER TABLE "ROSENHOFF"."PUBLIC"."POLL" ADD "KOMMER" boolean NOT NULL ;


--CREATE TABLE "PUBLIC"."PERSON"
--(
--   ID bigint PRIMARY KEY NOT NULL,
--   NAVN varchar(30) DEFAULT '' NOT NULL,
--   EMAIL varchar(30) DEFAULT NULL,
--   MOBIL varchar(15) DEFAULT NULL,
--   IMAGE_EXTENSION varchar(6)
--)
--;
--CREATE UNIQUE INDEX PRIMARY_KEY_C ON "PUBLIC"."PERSON"(ID)
--;
--insert into PERSON(NAVN,EMAIL,MOBIL,IMAGE_EXTENSION)
--select distinct NAVN,EMAIL,MOBIL,IMAGE_EXTENSION from SPILLER
--;
alter TABLE "PUBLIC"."SPILLER" add PERSON_ID BIGINT
--;
--update SPILLER s
--set s.PERSON_ID = (select p.id from PERSON p where p.NAVN = s.NAVN)
--;

--SØRG FOR Å KOPIERE RIKTIG ID TIL PERSON_ID I SPILLER

ALTER TABLE SPILLER DROP COLUMN "NAVN"
ALTER TABLE SPILLER DROP COLUMN "EMAIL"
ALTER TABLE SPILLER DROP COLUMN "MOBIL"
ALTER TABLE SPILLER DROP COLUMN "IMAGE_EXTENSION"
;
--ALTER TABLE SPILLER ADD CONSTRAINT fk_spiller_person FOREIGN KEY ( PERSON_ID ) REFERENCES PERSON ( ID )
--;
--CREATE   INDEX fk_child_idx ON SPILLER ( "PERSON_ID" )
;
ALTER TABLE "ROSENHOFF"."PUBLIC"."SPILLER" ALTER COLUMN "PERSON_ID" bigint  NOT NULL
;
delete from POLL
;
ALTER TABLE "ROSENHOFF"."PUBLIC"."POLL" ADD "PERSON_ID" integer NOT NULL
;
ALTER TABLE POLL DROP COLUMN "SPILLER_ID"
;
ALTER TABLE POLL ADD CONSTRAINT fk_poll_person FOREIGN KEY ( PERSON_ID ) REFERENCES PERSON ( ID );
CREATE   INDEX fki_poll_person ON POLL ( "PERSON_ID" );



