CREATE TABLE "PUBLIC"."AKTIVITET"
(
   ID integer PRIMARY KEY NOT NULL,
   NAAR timestamp DEFAULT 'null' NOT NULL,
   HVA varchar(50) DEFAULT '' NOT NULL,
   HVOR integer NOT NULL,
   FERDIG time DEFAULT '00:00:00' NOT NULL,
   SESONG varchar(15) NOT NULL,
   LAG_NAVN varchar(10) DEFAULT 'HOCKEY' NOT NULL,
   POLL boolean DEFAULT 'true' NOT NULL
)
;
CREATE TABLE "PUBLIC"."AKTIVITET_STED"
(
   ID integer PRIMARY KEY NOT NULL,
   STEDSNAVN varchar(30) NOT NULL
)
;
CREATE TABLE "PUBLIC"."BRUKER"
(
   ID integer PRIMARY KEY NOT NULL,
   BRUKERNAVN varchar(15) DEFAULT '' NOT NULL,
   PASSORD varchar(15) DEFAULT '' NOT NULL
)
;
CREATE TABLE "PUBLIC"."KAMP"
(
   ID integer PRIMARY KEY NOT NULL,
   MOTSTANDER varchar(30) DEFAULT '' NOT NULL,
   DATO date DEFAULT '0000-00-00' NOT NULL,
   HJEMME varchar(10) DEFAULT '' NOT NULL,
   MAAL_SCORET integer DEFAULT '0' NOT NULL,
   MAAL_SLUPPET_INN integer DEFAULT '0' NOT NULL,
   BESKRIVELSE varchar(200) DEFAULT NULL,
   SESONG varchar(15),
   LAG_NAVN varchar(10) DEFAULT 'HOCKEY' NOT NULL
)
;
CREATE TABLE "PUBLIC"."KAMP_SPILLER"
(
   KAMP_SPILLER_ID integer PRIMARY KEY NOT NULL,
   SPILLER_ID integer,
   KAMP_ID integer
)
;
CREATE TABLE "PUBLIC"."NYHET"
(
   NYHET_ID integer PRIMARY KEY NOT NULL,
   NYHET_TXT varchar(2000) NOT NULL,
   AKTIV boolean NOT NULL,
   TIDLAGTINN timestamp,
   SESONG varchar(15) DEFAULT 'SESONG_2009' NOT NULL,
   LAG_NAVN varchar(10) DEFAULT 'HOCKEY' NOT NULL,
   OVERSKRIFT varchar(100) DEFAULT 'Tom' NOT NULL
)
;
CREATE TABLE "PUBLIC"."PERSON"
(
   ID bigint PRIMARY KEY NOT NULL,
   NAVN varchar(30) DEFAULT '' NOT NULL,
   EMAIL varchar(30) DEFAULT NULL,
   MOBIL varchar(15) DEFAULT NULL,
   IMAGE_EXTENSION varchar(6)
)
;
CREATE TABLE "PUBLIC"."POENG"
(
   ID integer PRIMARY KEY NOT NULL,
   SPILLER integer DEFAULT '0' NOT NULL,
   ERPASS boolean,
   SESONG varchar(15),
   LAG_NAVN varchar(10) DEFAULT 'HOCKEY' NOT NULL,
   KAMP_ID integer NOT NULL,
   ANT_POENG integer NOT NULL
)
;
CREATE TABLE "PUBLIC"."POLL"
(
   ID integer PRIMARY KEY NOT NULL,
   AKTIVITET_ID integer NOT NULL,
   LABEL varchar(10) DEFAULT 'TEST',
   KOMMER boolean NOT NULL,
   PERSON_ID integer
)
;
CREATE TABLE "PUBLIC"."RAPPORT"
(
   ID integer PRIMARY KEY NOT NULL,
   KAMP integer DEFAULT '0' NOT NULL,
   OVERSKRIFT varchar(50) DEFAULT NULL,
   TEKST clob,
   SESONG varchar(15),
   LAG_NAVN varchar(10) DEFAULT 'HOCKEY' NOT NULL
)
;
CREATE TABLE "PUBLIC"."SPILLER"
(
   ID integer PRIMARY KEY NOT NULL,
   POSISJON varchar(3) NOT NULL,
   SESONG varchar(15) NOT NULL,
   LAG_NAVN varchar(10) DEFAULT 'HOCKEY' NOT NULL,
   PERSON_ID bigint NOT NULL
)
;
ALTER TABLE "PUBLIC"."AKTIVITET"
ADD CONSTRAINT FK_AKTIVITET_STED
FOREIGN KEY (HVOR)
REFERENCES "PUBLIC"."AKTIVITET_STED"(HVOR)
;
CREATE UNIQUE INDEX PRIMARY_KEY_8782 ON "PUBLIC"."AKTIVITET"(ID)
;
CREATE INDEX FK_AKTIVITET_STED_INDEX_8 ON "PUBLIC"."AKTIVITET"(HVOR)
;
CREATE UNIQUE INDEX PRIMARY_KEY_7A ON "PUBLIC"."AKTIVITET_STED"(ID)
;
CREATE UNIQUE INDEX CONSTRAINT_INDEX_7 ON "PUBLIC"."AKTIVITET_STED"(STEDSNAVN)
;
CREATE UNIQUE INDEX PRIMARY_KEY_7 ON "PUBLIC"."BRUKER"(ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_8 ON "PUBLIC"."KAMP"(ID)
;
ALTER TABLE "PUBLIC"."KAMP_SPILLER"
ADD CONSTRAINT KAMP_SPILLER_LAMP_FK
FOREIGN KEY (KAMP_ID)
REFERENCES "PUBLIC"."KAMP"(KAMP_ID)
;
ALTER TABLE "PUBLIC"."KAMP_SPILLER"
ADD CONSTRAINT KAMP_SPILLER_SPILLER_FK
FOREIGN KEY (SPILLER_ID)
REFERENCES "PUBLIC"."SPILLER"(SPILLER_ID)
;
CREATE UNIQUE INDEX KAMP_SPILLER_UNIQUE ON "PUBLIC"."KAMP_SPILLER"
(
  KAMP_ID,
  SPILLER_ID
)
;
CREATE INDEX KAMP_SPILLER_SPILLER_FK_INDEX_1 ON "PUBLIC"."KAMP_SPILLER"(SPILLER_ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_1 ON "PUBLIC"."KAMP_SPILLER"(KAMP_SPILLER_ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_14E3 ON "PUBLIC"."NYHET"(NYHET_ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_C ON "PUBLIC"."PERSON"(ID)
;
ALTER TABLE "PUBLIC"."POENG"
ADD CONSTRAINT FK_POENG_KAMP
FOREIGN KEY (KAMP_ID)
REFERENCES "PUBLIC"."KAMP"(KAMP_ID)
;
ALTER TABLE "PUBLIC"."POENG"
ADD CONSTRAINT POENG_SPILLER
FOREIGN KEY (SPILLER)
REFERENCES "PUBLIC"."SPILLER"(SPILLER)
;
CREATE INDEX POENG_SPILLER_INDEX_1 ON "PUBLIC"."POENG"(SPILLER)
;
CREATE INDEX FK_POENG_KAMP_INDEX_4 ON "PUBLIC"."POENG"(KAMP_ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_14 ON "PUBLIC"."POENG"(ID)
;
ALTER TABLE "PUBLIC"."POLL"
ADD CONSTRAINT FK_POLL_PERSON
FOREIGN KEY (PERSON_ID)
REFERENCES "PUBLIC"."PERSON"(PERSON_ID)
;
CREATE INDEX FK_POLL_AKTIVITET_INDEX_2 ON "PUBLIC"."POLL"(AKTIVITET_ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_B8 ON "PUBLIC"."POLL"(ID)
;
CREATE INDEX FKI_POLL_PERSON ON "PUBLIC"."POLL"(PERSON_ID)
;
CREATE INDEX FK_POLL_PERSON_INDEX_2 ON "PUBLIC"."POLL"(PERSON_ID)
;
ALTER TABLE "PUBLIC"."RAPPORT"
ADD CONSTRAINT FK_RAPPORT_KAMP
FOREIGN KEY (KAMP)
REFERENCES "PUBLIC"."KAMP"(KAMP)
;
CREATE INDEX FK_RAPPORT_KAMP_INDEX_6 ON "PUBLIC"."RAPPORT"(KAMP)
;
CREATE UNIQUE INDEX PRIMARY_KEY_8781 ON "PUBLIC"."RAPPORT"(ID)
;
ALTER TABLE "PUBLIC"."SPILLER"
ADD CONSTRAINT FK_SPILLER_PERSON
FOREIGN KEY (PERSON_ID)
REFERENCES "PUBLIC"."PERSON"(PERSON_ID)
;
CREATE UNIQUE INDEX PRIMARY_KEY_8DE ON "PUBLIC"."SPILLER"(ID)
;
CREATE INDEX FK_CHILD_IDX ON "PUBLIC"."SPILLER"(PERSON_ID)
;
